/*
===============================================================================
DDL: Silver layer table creation
===============================================================================
Purpose:
    Create the structure of the Silver layer tables from the data received in
    Bronze.

    Unlike Bronze, Silver holds data that is subsequently cleaned,
    standardized and transformed to make it easier to integrate and consume in
    the Gold layer.

    The tables are dropped and recreated if they already exist, so the script
    can be run again during development and their structure redefined.

    In addition, each table includes dwh_create_date to record when the record
    was inserted into the Data Warehouse.
===============================================================================
*/

/*
SQLCMD script: run it with -v DatabaseName="<database>". The variable is
required and has no default.
*/

USE [$(DatabaseName)];
GO


/*
-------------------------------------------------------------------------------
CRM: Customer information
-------------------------------------------------------------------------------

The structure keeps the main columns coming from Bronze.

The dwh_create_date column does not come from the original source. It is an
audit attribute generated by the Data Warehouse through DEFAULT GETDATE().
It records when the record was created within Silver.
-------------------------------------------------------------------------------
*/

IF OBJECT_ID('silver.crm_cust_info', 'U') IS NOT NULL
    DROP TABLE silver.crm_cust_info;
GO

CREATE TABLE silver.crm_cust_info (
    cst_id              INT,
    cst_key             NVARCHAR(50),
    cst_firstname       NVARCHAR(50),
    cst_lastname        NVARCHAR(50),
    cst_marital_status  NVARCHAR(50),
    cst_gndr            NVARCHAR(50),
    cst_create_date     DATE,
    dwh_create_date     DATETIME2 DEFAULT GETDATE()
);


/*
-------------------------------------------------------------------------------
CRM: Product information
-------------------------------------------------------------------------------

Silver adds cat_id, which later makes it possible to link the products with
the category information coming from the ERP.

Dates are stored as DATE because the original values are validated and
converted during the transformation from Bronze.
-------------------------------------------------------------------------------
*/

IF OBJECT_ID('silver.crm_prd_info', 'U') IS NOT NULL
    DROP TABLE silver.crm_prd_info;
GO

CREATE TABLE silver.crm_prd_info (
    prd_id              INT,
    cat_id              NVARCHAR(50),
    prd_key             NVARCHAR(50),
    prd_nm              NVARCHAR(50),
    prd_cost            INT,
    prd_line            NVARCHAR(50),
    prd_start_dt        DATE,
    prd_end_dt          DATE,
    dwh_create_date     DATETIME2 DEFAULT GETDATE()
);


/*
-------------------------------------------------------------------------------
CRM: Sales details
-------------------------------------------------------------------------------

Unlike Bronze, the order, shipping and due dates are stored as DATE.

This reflects a transformation done during the Silver load, where the original
values coming from Bronze are validated and converted to a suitable date type.
-------------------------------------------------------------------------------
*/

IF OBJECT_ID('silver.crm_sales_details', 'U') IS NOT NULL
    DROP TABLE silver.crm_sales_details;
GO

CREATE TABLE silver.crm_sales_details (
    sls_ord_num         NVARCHAR(50),
    sls_prd_key         NVARCHAR(50),
    sls_cust_id         INT,
    sls_order_dt        DATE,
    sls_ship_dt         DATE,
    sls_due_dt          DATE,
    sls_sales           INT,
    sls_quantity        INT,
    sls_price           INT,
    dwh_create_date     DATETIME2 DEFAULT GETDATE()
);


/*
-------------------------------------------------------------------------------
ERP: Additional customer information
-------------------------------------------------------------------------------

This table keeps the birthdate and gender information coming from the ERP
system.

This information is later integrated with the customer data coming from the
CRM in the Gold layer.
-------------------------------------------------------------------------------
*/

IF OBJECT_ID('silver.erp_cust_az12', 'U') IS NOT NULL
    DROP TABLE silver.erp_cust_az12;
GO

CREATE TABLE silver.erp_cust_az12 (
    cid                 NVARCHAR(50),
    bdate               DATE,
    gen                 NVARCHAR(50),
    dwh_create_date     DATETIME2 DEFAULT GETDATE()
);


/*
-------------------------------------------------------------------------------
ERP: Customer location
-------------------------------------------------------------------------------

Holds the geographic information coming from the ERP.

The table is later used to complement the customer dimension in the Gold
layer.
-------------------------------------------------------------------------------
*/

IF OBJECT_ID('silver.erp_loc_a101', 'U') IS NOT NULL
    DROP TABLE silver.erp_loc_a101;
GO

CREATE TABLE silver.erp_loc_a101 (
    cid                 NVARCHAR(50),
    cntry               NVARCHAR(50),
    dwh_create_date     DATETIME2 DEFAULT GETDATE()
);


/*
-------------------------------------------------------------------------------
ERP: Product categories and subcategories
-------------------------------------------------------------------------------

Holds the product categorization information coming from the ERP.

This information is later integrated with the products coming from the CRM to
build the product dimension in Gold.
-------------------------------------------------------------------------------
*/

IF OBJECT_ID('silver.erp_px_cat_g1v2', 'U') IS NOT NULL
    DROP TABLE silver.erp_px_cat_g1v2;
GO

CREATE TABLE silver.erp_px_cat_g1v2 (
    id                  NVARCHAR(50),
    cat                 NVARCHAR(50),
    subcat              NVARCHAR(50),
    maintenance         NVARCHAR(50),
    dwh_create_date     DATETIME2 DEFAULT GETDATE()
);